spring:
  application:
    name: consumer
server:
  port: 8002

#通过ip地址访问服务提供者
user:
  userServiceUrl: http://localhost:8000
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true                           
    fetchRegistry: true                                
    serviceUrl:                                        
      defaultZone: http://192.168.202.128:8761/eureka/